events {}

http {
  access_log /var/log/nginx/access.log;
  error_log  /var/log/nginx/error.log warn;

  server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

     location /reports/ {
      alias /reports/;
      try_files $uri =404;
    }
  }
}