services:
  web:
    image: nginx:alpine
    container_name: web
    ports:
      - "8082:80"
    volumes:
      - ./nginx-static:/usr/share/nginx/html:ro
      - ./nginx-logs:/var/log/ngi
        ¿docker ps te f- ./nginx-logs:/var/log/nginx
